IF NOT EXISTS (SELECT * FROM sysobjects WHERE type = 'U' AND name = 'CLIENTE')
BEGIN
	CREATE TABLE CLIENTE (
		ID INT PRIMARY KEY,
	    NOME VARCHAR(25) NOT NULL,
		SOBRENOME VARCHAR (65) NOT NULL,
		DTNASC SMALLDATETIME NOT NULL,
		SEXO CHAR(1) NOT NULL,
		EMAIL VARCHAR(100) NOT NULL,
		ATIVO BIT NOT NULL,    
	)
END

IF NOT EXISTS (SELECT * FROM sysobjects WHERE type = 'U' AND name = 'PRODUTO')
BEGIN
	CREATE TABLE PRODUTO (
		IDPROD INT NOT NULL,
	    IDCLI INT NOT NULL,
		NOMEPROD VARCHAR (50) NOT NULL
		PRIMARY KEY(IDPROD, IDCLI)
	)
END
